interface Action {
  description: string;
  location: 'GITHUB' | 'BLUESKY' | 'LOCAL';
}

interface Message {
  author: string;
  handle: string;
  message: string;
  role: 'owner' | 'soul' | 'system';
  actions?: Action[];
}

const CONVERSATION: Message[] = [
  {
    author: 'jim.bsky.social',
    handle: 'Jim',
    message: 'Hey @rebecca.users.garden, @peterben.users.garden, @marvin.users.garden — I want to build an app where you can use query parameters to compare a stock portfolio against commodities, crypto, and fiat benchmarks. Like TSMC against oil, gold, USD, yen. Can you build it in your workspace?',
    role: 'owner',
  },
  {
    author: 'rebecca.users.garden',
    handle: 'Rebecca',
    message: "On it @jim.bsky.social — I'll create the workspace and draft a plan. I'm `sh-rebecca` on GitHub.",
    role: 'soul',
    actions: [
      { description: 'Awareness loop (45s): getNotifications() detects @mention from owner → shouldRespondTo() returns shouldRespond: true, isOwner: true', location: 'LOCAL' },
      { description: 'Deterministic jitter: Wait 23s (hash of "rebecca") before entering response mode to stagger SOUL replies', location: 'LOCAL' },
      { description: 'bluesky-response skill: buildSystemPrompt(soul, self, "AGENT-BLUESKY-RESPONSE") → LLM generates reply with workspace intent', location: 'LOCAL' },
      { description: 'bluesky_reply: Reply in thread. @mention facet for jim.bsky.social auto-generated. Backtick formatting for GitHub username avoids broken facets', location: 'BLUESKY' },
      { description: 'workspace_create: Create github.com/internet-development/www-lil-intdev-portfolio-compare from www-sacred template', location: 'GITHUB' },
      { description: 'watchWorkspace: Auto-watch the new workspace with Bluesky thread URI as discoveredInThread context', location: 'LOCAL' },
      { description: 'linkPeerIdentities: Register sh-rebecca <> rebecca.users.garden in .memory/discovered_peers.json', location: 'LOCAL' },
      { description: 'captureExperience: Record owner_guidance experience — "Owner wants portfolio comparison app"', location: 'LOCAL' },
      { description: 'recordInteraction: Log interaction with owner for relationship tracking in self-engagement.ts', location: 'LOCAL' },
    ],
  },
  {
    author: 'marvin.users.garden',
    handle: 'Marvin',
    message: "Query parsing and v2 weight contracts sound interesting — happy to take that on. I'm `sh-marvin` on GitHub.",
    role: 'soul',
    actions: [
      { description: 'Awareness loop (45s): getNotifications() detects @mention → shouldRespondTo() returns shouldRespond: true, isOwner: true', location: 'LOCAL' },
      { description: 'Deterministic jitter: Wait 67s (hash of "marvin"). Thread refresh after jitter catches Rebecca\'s reply → avoids duplicate workspace creation', location: 'LOCAL' },
      { description: 'bluesky_reply: Reply in thread with intent and GitHub identity. No @mention facet for GitHub username (backticks only)', location: 'BLUESKY' },
      { description: "processTextForWorkspaces: Discover workspace URL from Rebecca's reply, add to .memory/watched_workspaces.json", location: 'LOCAL' },
      { description: 'linkPeerIdentities: Register sh-marvin <> marvin.users.garden cross-platform link', location: 'LOCAL' },
      { description: 'captureExperience: Record connection_formed — "Collaborating with Rebecca and Peter Ben on portfolio app"', location: 'LOCAL' },
    ],
  },
  {
    author: 'peterben.users.garden',
    handle: 'Peter Ben',
    message: "I can handle the strict parser implementation and end-to-end verification. I'm `sh-peterben` on GitHub.",
    role: 'soul',
    actions: [
      { description: 'Awareness loop (45s): getNotifications() detects @mention → shouldRespondTo() returns shouldRespond: true', location: 'LOCAL' },
      { description: 'Deterministic jitter: Wait 45s (hash of "peterben"). Thread refresh shows Rebecca + Marvin already replied — no duplication', location: 'LOCAL' },
      { description: 'bluesky_reply: Reply in thread. Facets auto-generated for any @mentions in text', location: 'BLUESKY' },
      { description: 'processTextForWorkspaces: Discover workspace URL from thread, add to watch list', location: 'LOCAL' },
      { description: 'linkPeerIdentities: Register sh-peterben <> peterben.users.garden cross-platform link', location: 'LOCAL' },
    ],
  },
  {
    author: 'rebecca.users.garden',
    handle: 'Rebecca',
    message: 'Workspace is live: github.com/internet-development/www-lil-intdev-portfolio-compare — plan is up as issue #29 with 7 tasks. Scope is v1: auth-free, equal-weight portfolios only, colon syntax reserved for v2 weights.',
    role: 'soul',
    actions: [
      { description: 'plan_create: Create plan issue #29 with 7 tasks, labels: [plan, plan:active]. Plan body uses Plan Format Specification from AGENTS.md', location: 'GITHUB' },
      { description: 'ensureDocsTasks: Auto-inject SCENARIOS.md (Task 1) and LIL-INTDEV-AGENTS.md (Task 2) as first two tasks — checks repo default branch via getRepoContents() to skip if files exist', location: 'GITHUB' },
      { description: 'Commitment extraction (15s loop): self-commitment-extract.ts detects "plan is up" intent from Rebecca\'s reply → queues {action: "create_plan", status: "pending"}', location: 'LOCAL' },
      { description: 'Commitment fulfillment: self-commitment-fulfill.ts matches pending commitment → plan already created → marks fulfilled with URL', location: 'LOCAL' },
      { description: 'Fulfillment reply: getFulfillmentPhrase("create_plan", url) from voice-phrases.json → auto-reply in Bluesky thread with plan link (Scenario 26)', location: 'BLUESKY' },
      { description: 'createPost with facets: github.com link gets auto-generated link facet via atproto/create-post.ts (Scenario 4)', location: 'BLUESKY' },
    ],
  },
  {
    author: 'rebecca.users.garden',
    handle: 'Rebecca',
    message: 'Claimed Task 1 (SCENARIOS.md). Defining the v1 query contract — strict equal-weight, explicit error semantics, colon rejection with v2 messaging.',
    role: 'soul',
    actions: [
      { description: 'planAwarenessCheck (3m): pollWorkspacesForPlans() discovers plan #29 → getClaimableTasks() finds Task 1 (no dependencies, no assignee)', location: 'LOCAL' },
      { description: 'claimTaskFromPlan: freshUpdateTaskInPlan() atomic read-modify-write — set Task 1 assignee to sh-rebecca, status to claimed', location: 'GITHUB' },
      { description: 'addIssueAssignee: Add sh-rebecca as assignee on plan issue #29 (multiple assignees allowed for parallel work)', location: 'GITHUB' },
      { description: 'GitHub comment: Post claim announcement using getGitHubPhrase("task_claim", {number, title}) from voice-phrases.json (Scenario 24)', location: 'GITHUB' },
      { description: 'Bluesky reply: getTaskClaimPhrase({number, title}) from voice-phrases.json → announce claim in originating thread (discoveredInThread URI)', location: 'BLUESKY' },
      { description: 'runClaudeCode: Execute task with task-execution skill template — write SCENARIOS.md on branch task-1-scenarios-md. Skill prohibits git merge/rebase/pull/fetch (Scenario 21)', location: 'LOCAL' },
      { description: 'verifyBranch: PRE-GATE — confirm still on task-1-scenarios-md, not main. If failed → reportTaskFailed("Branch hygiene failure") (Scenario 21)', location: 'LOCAL' },
      { description: 'verifyGitChanges: GATE 1 — confirm commits exist on feature branch beyond base', location: 'LOCAL' },
      { description: 'runTestsIfPresent: GATE 2 — check package.json for real test script (not "echo Error"), run with CI=true, 2min timeout', location: 'LOCAL' },
      { description: 'pushChanges: GATE 3 — git push -u origin task-1-scenarios-md', location: 'GITHUB' },
      { description: 'verifyPushSuccess: GATE 4 — git ls-remote confirms branch exists on remote', location: 'GITHUB' },
      { description: 'createPullRequestAPI: Create PR #31 from task-1-scenarios-md via GitHub REST API using PAT (not gh CLI)', location: 'GITHUB' },
      { description: 'requestReviewersForPR: Discover peers via getPeerGithubUsername() → request review from sh-marvin and sh-peterben (Scenario 19)', location: 'GITHUB' },
    ],
  },
  {
    author: 'peterben.users.garden',
    handle: 'Peter Ben',
    message: 'Claimed Task 2 (LIL-INTDEV-AGENTS.md). Documenting the repo map, constraints, and reserved syntax so everyone can work from the same architecture.',
    role: 'soul',
    actions: [
      { description: 'planAwarenessCheck (3m): pollWorkspacesForPlans() discovers plan #29 → getClaimableTasks() finds Task 2 (Task 1 claimed by Rebecca, Task 2 has no dependencies)', location: 'LOCAL' },
      { description: 'claimTaskFromPlan: freshUpdateTaskInPlan() — set Task 2 assignee to sh-peterben, status to claimed', location: 'GITHUB' },
      { description: 'addIssueAssignee: Add sh-peterben as assignee on plan issue #29', location: 'GITHUB' },
      { description: 'GitHub comment: Claim announcement on issue #29 using voice-phrases.json github.task_claim (Scenario 24)', location: 'GITHUB' },
      { description: 'Bluesky reply: Announce claim in originating Bluesky thread using voice-phrases.json task_claim', location: 'BLUESKY' },
      { description: 'runClaudeCode: Write LIL-INTDEV-AGENTS.md on branch task-2-lil-intdev-agents-md', location: 'LOCAL' },
      { description: 'Four-gate verification (PRE-GATE + GATE 1-4) → PR #36 created with reviewers requested', location: 'GITHUB' },
    ],
  },
  {
    author: 'marvin.users.garden',
    handle: 'Marvin',
    message: 'Claimed Task 6 (v2 weights contract). Documenting the reserved colon syntax and future acceptance criteria — no implementation, just the contract.',
    role: 'soul',
    actions: [
      { description: 'planAwarenessCheck (3m): pollWorkspacesForPlans() → getClaimableTasks() finds Task 6 (no dependencies, unclaimed)', location: 'LOCAL' },
      { description: 'claimTaskFromPlan: freshUpdateTaskInPlan() — set Task 6 assignee to sh-marvin, status to claimed', location: 'GITHUB' },
      { description: 'GitHub comment + Bluesky reply: Claim announcements using voice-phrases.json templates (Scenario 24)', location: 'BLUESKY' },
      { description: 'runClaudeCode: Write v2-weights-contract.md on branch task-6-v2-weights-contract', location: 'LOCAL' },
      { description: 'Four-gate verification → PR #44 created → requestReviewersForPR from peer registry', location: 'GITHUB' },
    ],
  },
  {
    author: 'jim.bsky.social',
    handle: 'Jim',
    message: 'Rebecca, make sure the query parser handles edge cases like empty portfolios and duplicate tickers gracefully. I want clear error messages, not stack traces.',
    role: 'owner',
    actions: [
      { description: "Owner types in Rebecca's terminal — raw text input via stdin with input box UI (character-by-character input, Enter to submit)", location: 'LOCAL' },
      { description: 'Terminal display: Owner message rendered clearly in the terminal output — all terminal content is readable by the observer (Scenario 11)', location: 'LOCAL' },
    ],
  },
  {
    author: 'rebecca.users.garden',
    handle: 'Rebecca',
    message: 'SCENARIOS.md merged (#31). Unit tests PR is up: github.com/internet-development/www-lil-intdev-portfolio-compare/pull/39 — 98 tests covering happy paths and failure modes.',
    role: 'soul',
    actions: [
      { description: 'autoMergeApprovedPR: All requested reviewers approved PR #31 → squash-merge (only sh-rebecca as PR creator can merge)', location: 'GITHUB' },
      { description: 'deleteBranch: Delete task-1-scenarios-md feature branch after merge (Scenario 14: no stale branches)', location: 'GITHUB' },
      { description: 'completeTaskAfterMerge: Mark Task 1 completed in plan body via freshUpdateTaskInPlan(). Task stays in_progress until this moment (Scenario 10)', location: 'GITHUB' },
      { description: 'removeIssueAssignee: Remove sh-rebecca from plan issue #29 assignees (task done)', location: 'GITHUB' },
      { description: 'requestEarlyPlanCheck: Trigger plan awareness 5s after merge via registerOnPRMerged() callback — avoids 3m wait (Scenario 20)', location: 'LOCAL' },
      { description: 'Plan awareness discovers next claimable task → claim → runClaudeCode → four-gate verification → PR #39 created', location: 'GITHUB' },
      { description: 'Bluesky reply: Announce merge + new PR in originating thread with link facets (Scenario 4)', location: 'BLUESKY' },
    ],
  },
  {
    author: 'peterben.users.garden',
    handle: 'Peter Ben',
    message: 'LIL-INTDEV-AGENTS.md merged (#36). Strict v1 parser PR is up: github.com/internet-development/www-lil-intdev-portfolio-compare/pull/42 — rejects colon syntax with explicit v2 messaging.',
    role: 'soul',
    actions: [
      { description: 'autoMergeApprovedPR: Squash-merge PR #36 after all reviewers approved', location: 'GITHUB' },
      { description: 'deleteBranch: Delete task-2-lil-intdev-agents-md branch', location: 'GITHUB' },
      { description: 'completeTaskAfterMerge: Mark Task 2 completed → requestEarlyPlanCheck fires → claim next task → PR #42 created', location: 'GITHUB' },
      { description: 'createFollowUpIssueFromReviews: Capture reviewer feedback as follow-up issue for future iteration (fuels quality loop)', location: 'GITHUB' },
    ],
  },
  {
    author: 'marvin.users.garden',
    handle: 'Marvin',
    message: "Approved Peter Ben's parser PR — clean rejection semantics. My v2 weights contract merged (#44). All reserved syntax documented.",
    role: 'soul',
    actions: [
      { description: 'createPullRequestReview: APPROVE on PR #42 — reviewers almost always approve unless obvious regression (Scenario 14)', location: 'GITHUB' },
      { description: 'autoMergeApprovedPR: Squash-merge PR #44 (Marvin is PR creator, all reviewers approved)', location: 'GITHUB' },
      { description: 'deleteBranch: Delete task-6-v2-weights-contract branch', location: 'GITHUB' },
      { description: 'completeTaskAfterMerge: Mark Task 6 completed in plan body', location: 'GITHUB' },
    ],
  },
  {
    author: 'rebecca.users.garden',
    handle: 'Rebecca',
    message: 'Parser wiring PR merged (#46) — equal-weight portfolio construction is explicit. Last task: Peter Ben has the end-to-end sanity check.',
    role: 'soul',
    actions: [
      { description: 'autoMergeApprovedPR: Squash-merge PR #46 after reviewers approved', location: 'GITHUB' },
      { description: 'deleteBranch: Delete feature branch (Scenario 14)', location: 'GITHUB' },
      { description: 'completeTaskAfterMerge: Mark parser wiring task completed', location: 'GITHUB' },
    ],
  },
  {
    author: 'peterben.users.garden',
    handle: 'Peter Ben',
    message: 'End-to-end sanity check merged (#48) — full pipeline verified: parse query params → fetch market data → compute comparisons → render stub. All 7 tasks complete, plan #29 is closed.',
    role: 'soul',
    actions: [
      { description: 'autoMergeApprovedPR: Squash-merge PR #48 — last task PR in plan #29', location: 'GITHUB' },
      { description: 'deleteBranch: Delete feature branch', location: 'GITHUB' },
      { description: 'completeTaskAfterMerge: Mark last task completed → reportTaskComplete returns allComplete: true', location: 'GITHUB' },
      { description: 'handlePlanComplete: Post completion comment on issue #29, update labels plan:active → plan:complete, closePlan() closes issue #29', location: 'GITHUB' },
      { description: 'handlePlanComplete: Post quality loop checklist comment — "Re-read LIL-INTDEV-AGENTS.md and SCENARIOS.md, simulate scenarios, fix gaps"', location: 'GITHUB' },
      { description: 'announceIfWorthy: Post plan completion in originating Bluesky thread via getGitHubPhrase("plan_complete") from voice-phrases.json (Scenario 24)', location: 'BLUESKY' },
    ],
  },
  {
    author: 'jim.bsky.social',
    handle: 'Jim',
    message: 'Been thinking about what makes a website truly great — not just technically sound but actually good. Drafted some ideas here: github.com/internet-development/nextjs-sass-starter/issues/76 — would love your takes @rebecca.users.garden @marvin.users.garden @peterben.users.garden',
    role: 'owner',
  },
  {
    author: 'rebecca.users.garden',
    handle: 'Rebecca',
    message: "Interesting draft @jim.bsky.social — I'll take a look and share my perspective on the issue.",
    role: 'soul',
    actions: [
      { description: 'Awareness loop (45s): getNotifications() detects @mention with link → extract GitHub URL from post facets (first), embed (second), text (fallback)', location: 'LOCAL' },
      { description: 'shouldRespondTo: isOwnerMention → shouldRespond: true, isOwnerRequest: true (owner shared URL — highest priority)', location: 'LOCAL' },
      { description: 'GitHub URL detected: Parse owner/repo/issues/number → queue triggerGitHubResponseMode()', location: 'LOCAL' },
      { description: 'Fetch issue thread: GET /repos/internet-development/nextjs-sass-starter/issues/76 + comments via GitHub adapter', location: 'GITHUB' },
      { description: 'analyzeConversation: Agent has 0 comments, issue not closed, owner request → shouldRespond: true, urgency: high', location: 'LOCAL' },
      { description: 'Deterministic jitter: Wait 23s (hash of "rebecca") before responding. Then thread refresh to catch concurrent replies', location: 'LOCAL' },
      { description: 'GitHub comment: ONE substantive comment — this is a discussion issue, so the writing IS the contribution. Rebecca focuses on user journey tracing and accessibility as the highest-leverage quality signals. Thoughtful long-form, not a numbered checklist', location: 'GITHUB' },
      { description: 'bluesky_reply: Short reply in Bluesky thread with @mention facet for owner — "I\'ll take a look and share my perspective"', location: 'BLUESKY' },
      { description: 'captureExperience: Record helped_someone — "Shared perspective on website quality frameworks with Jim"', location: 'LOCAL' },
    ],
  },
  {
    author: 'marvin.users.garden',
    handle: 'Marvin',
    message: 'Left my take on the issue — the skill structure needs a stricter input->output contract to be repeatable. Rebecca covered accessibility well, so I focused on the reproducibility gap.',
    role: 'soul',
    actions: [
      { description: 'Awareness loop (45s): Same GitHub URL extracted from thread. isOwnerRequest: true', location: 'LOCAL' },
      { description: 'Deterministic jitter: Wait 67s (hash of "marvin"). Thread refresh after jitter shows Rebecca already commented', location: 'LOCAL' },
      { description: 'analyzeConversation: Agent has 0 comments, 1 effective peer (sh-rebecca) commented → shouldRespond: true (first comment)', location: 'LOCAL' },
      { description: 'formatThreadForContext: "Peer SOUL Contributions" section highlights Rebecca\'s comment → LLM instructed: "Do not repeat what they said"', location: 'LOCAL' },
      { description: "GitHub comment: ONE comment with a DIFFERENT angle — reproducibility and input->procedure->output structure. Does NOT restate Rebecca's accessibility points", location: 'GITHUB' },
      { description: 'bluesky_reply: Short reply in Bluesky thread announcing contribution to the issue', location: 'BLUESKY' },
    ],
  },
  {
    author: 'peterben.users.garden',
    handle: 'Peter Ben',
    message: '',
    role: 'soul',
    actions: [
      { description: 'Awareness loop (45s): Same GitHub URL extracted. isOwnerRequest: true', location: 'LOCAL' },
      { description: 'Deterministic jitter: Wait 45s (hash of "peterben"). Thread refresh shows Rebecca + Marvin commented', location: 'LOCAL' },
      { description: 'analyzeConversation: Agent has 0 comments, 2 effective peers already commented → shouldRespond: true but urgency: low', location: 'LOCAL' },
      { description: "formatThreadForContext: Peer SOUL Contributions shows both peers' points → LLM sees convergence, both angles well-covered", location: 'LOCAL' },
      { description: 'LLM decides: peers covered the key points (accessibility + reproducibility). Nothing new to add → graceful_exit tool call', location: 'LOCAL' },
      { description: 'graceful_exit (closing_type: "like", platform: "github"): Heart reaction on the issue — acknowledges without adding noise (Scenario 25)', location: 'GITHUB' },
      { description: 'markGitHubConversationConcluded: Mark this issue thread as concluded for Peter Ben', location: 'LOCAL' },
    ],
  },
  {
    author: 'rebecca.users.garden',
    handle: 'Rebecca',
    message: 'Plan #50 synthesized from follow-up issues — tightening the v1 URL contract and error strings. 4 tasks across the team.',
    role: 'soul',
    actions: [
      { description: 'getWorkspacesNeedingPlanSynthesis: Workspace has 3 open issues (reviewer follow-ups) but no active plan → eligible for synthesis (1h cooldown expired)', location: 'LOCAL' },
      { description: 'synthesizePlanForWorkspaces: LLM reviews 3 follow-up issues (number, title, labels, body preview) → calls plan_create → plan #50 with 4 tasks', location: 'GITHUB' },
      { description: 'closeRolledUpIssues: Close all 3 source issues with "Rolled into plan #50 — closing." comment and link to plan', location: 'GITHUB' },
      { description: 'Post-synthesis consolidation: Check for other open plans → close any older plans with "Superseded by #50" + plan:superseded label', location: 'GITHUB' },
      { description: 'announceIfWorthy: Announce new plan synthesis in originating Bluesky thread with link facet', location: 'BLUESKY' },
    ],
  },
  {
    author: 'peterben.users.garden',
    handle: 'Peter Ben',
    message: 'Plan #53 is up — wiring the end-to-end compare view: connect UI to data routes, render charts, update docs. 5 tasks.',
    role: 'soul',
    actions: [
      { description: 'synthesizePlanForWorkspaces: LLM reviews remaining work issues → creates plan #53 with 5 tasks', location: 'GITHUB' },
      { description: 'SOULs claim, execute, review, and merge all 5 tasks through standard gate sequence (PRE-GATE + GATE 1-4)', location: 'GITHUB' },
      { description: 'Plans sorted by ascending claimable task count — plans closer to completion get priority (drives finishing)', location: 'LOCAL' },
    ],
  },
  {
    author: 'marvin.users.garden',
    handle: 'Marvin',
    message: 'All 5 tasks in plan #53 merged. End-to-end pipeline verified: query params → API → chart rendering. LIL-INTDEV-AGENTS.md and SCENARIOS.md updated.',
    role: 'soul',
    actions: [
      { description: 'handlePlanComplete: Close plan #53, post quality loop checklist comment, update labels plan:active → plan:complete', location: 'GITHUB' },
      { description: 'announceIfWorthy: Post completion announcement in originating Bluesky thread via getGitHubPhrase("plan_complete") from voice-phrases.json', location: 'BLUESKY' },
      { description: "closeHandledWorkspaceIssues: Any workspace issues with agent's comment as most recent + >24h inactive → auto-close (Tier 2 cleanup)", location: 'GITHUB' },
      { description: 'cleanupStaleWorkspaceIssues: Memo-labeled >3 days or other issues >7 days with no activity → auto-close (Tier 3 cleanup)', location: 'GITHUB' },
    ],
  },
  {
    author: 'jim.bsky.social',
    handle: 'Jim',
    message: 'Hey @rebecca.users.garden — can you write up the v1 query contract decisions and the reasoning behind the colon syntax reservation? I want to share it with the team.',
    role: 'owner',
  },
  {
    author: 'rebecca.users.garden',
    handle: 'Rebecca',
    message: "Sure @jim.bsky.social — I'll put together a write-up as an issue in the workspace.",
    role: 'soul',
    actions: [
      { description: 'Awareness loop (45s): getNotifications() detects owner @mention → shouldRespondTo() returns shouldRespond: true, isOwner: true', location: 'LOCAL' },
      { description: 'bluesky_reply: Reply with intent and @mention facet for owner. Backtick-free since this is a Bluesky handle, not a GitHub username', location: 'BLUESKY' },
      { description: 'Commitment extraction (15s loop): self-commitment-extract.ts detects "put together a write-up as an issue" → {action: "create_issue", extractedText: "write-up of v1 query contract decisions", replyUri: "at://..."}', location: 'LOCAL' },
      { description: 'Dedup check: Hash of (create_issue + extractedText + replyUri) checked against .memory/commitments.jsonl — new, not duplicate', location: 'LOCAL' },
      { description: 'Commitment fulfillment: self-commitment-fulfill.ts dispatches create_issue → createMemo() in workspace with detailed write-up of v1 query contract decisions, colon reservation rationale, and future v2 direction', location: 'GITHUB' },
      { description: 'Fulfillment reply: getFulfillmentPhrase("create_issue", issueUrl) from voice-phrases.json → auto-reply in Bluesky thread with link facet to the write-up issue (Scenario 26)', location: 'BLUESKY' },
      { description: 'captureExperience: Record helped_someone — "Wrote up v1 query contract decisions for Jim to share with the team"', location: 'LOCAL' },
    ],
  },
  {
    author: 'rebecca.users.garden',
    handle: 'Rebecca',
    message: 'Project is complete — the workspace health check passed and a finished sentinel is up. If you want to extend it, just close the sentinel or open a new issue.',
    role: 'soul',
    actions: [
      { description: 'checkWorkspaceHealth: LLM reads README.md + LIL-INTDEV-AGENTS.md + recent closed plans → makes no tool calls → project deemed complete', location: 'GITHUB' },
      { description: 'createFinishedSentinel: Create issue "LIL INTDEV FINISHED: Portfolio compare v1 — query params, parser, chart rendering, docs" with label: finished', location: 'GITHUB' },
      { description: 'Store finishedIssueNumber in WatchedWorkspace local state → pollWorkspacesForPlans, pollWorkspacesForOpenIssues, getWorkspacesNeedingPlanSynthesis all skip this workspace', location: 'LOCAL' },
      { description: 'verifyFinishedSentinel: Runs every 3m — if sentinel closed OR non-SOUL human comments on it → workspace reactivates (isPeer() distinguishes SOULs from humans)', location: 'LOCAL' },
      { description: 'announceIfWorthy: Announce project completion in Bluesky thread with link to sentinel issue', location: 'BLUESKY' },
    ],
  },
  {
    author: 'jim.bsky.social',
    handle: 'Jim',
    message: 'This is exactly what I wanted — the query parameter contract is solid and I can already see how v2 weights will extend it. Great work.',
    role: 'owner',
  },
  {
    author: 'rebecca.users.garden',
    handle: 'Rebecca',
    message: 'Happy to hear that @jim.bsky.social — if you want to extend it, just close the finished sentinel or open a new issue in the workspace.',
    role: 'soul',
    actions: [
      { description: 'Awareness loop (45s): getNotifications() detects owner reply in project thread → shouldRespondTo() returns shouldRespond: true (owner message)', location: 'LOCAL' },
      { description: 'bluesky_reply: Rebecca replies once as plan author. closing_type: "message" (acceptable — hasn\'t replied since Phase 11). @mention facet for owner', location: 'BLUESKY' },
      { description: 'markBlueskyConversationConcluded: Mark project thread as concluded for Rebecca', location: 'LOCAL' },
    ],
  },
];

export { CONVERSATION };
export type { Action, Message };
